name: CI

on:
  push:
    branches: [ main, ver/1.3.0 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov mypy black isort flake8

    - name: Run formatting check (Black)
      run: black --check .

    - name: Run import sort check (isort)
      run: isort --check-only .

    - name: Run linting (flake8)
      run: flake8 .

    - name: Run type checking (mypy)
      run: mypy --check-untyped-defs .

    - name: Run tests with coverage
      run: |
        pytest --cov=services --cov=models --cov=ui --cov=utils --cov=config --cov-report=xml
    - name: Upload coverage to Codecov
      if: success() && github.event_name != 'pull_request'
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml
