name: CI (pip)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.10, 3.11]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Create virtualenv & install deps
        run: |
          python -m venv .venv
          # Linux/macOS
          source .venv/bin/activate
          # Windows (PowerShell):
          #   .venv\Scripts\Activate.ps1
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Check formatting (Black)
        run: .venv/bin/black --check .

      - name: Check import sorting (isort)
        run: .venv/bin/isort --check-only .

      - name: Lint (Flake8)
        run: .venv/bin/flake8 .

      - name: Type-check (Mypy)
        run: .venv/bin/mypy .

      - name: Run tests
        run: .venv/bin/pytest -q --maxfail=1 --disable-warnings
